name: CI CD Docker

on:
  push:
    branches:
      - main # Jalan saat push ke branch main
      - master
  pull_request:
    branches:
      - main # Jalan saat PR ke branch main
      - master

jobs:
  build: # Nama job (bebas)
    runs-on: ubuntu-latest # Mesin virtual

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Prebuild action

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install Dependencies
        run: npm install

      # - name: Run Tests
      #   run: npm test --if-present

      - name: Build Success
        run: echo "Build Success"
